### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by aizvorski** [openmopac/mopac#117]
I'd like to confirm whether the whole repository is licensed under LGPL.

There are both "COPYING" and "COPYING.lesser" files, which would seem to suggest some parts are GPL and some LGPL.

A quick search through the F90 files shows all of them have a "MOPAC is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License" and "Copyright (C) 2021, Virginia Polytechnic Institute and State University" header; except for one file [getpdb.F90](https://github.com/openmopac/mopac/blob/main/src/makpol/getpdb.F90) which has no header (probably omitted by accided).

If the whole repository is LGPL, could we delete the file "COPYING", and add a note in README.md which also says the license as a whole is LGPL?

**Comment by godotalgorithm** [comment]
Yes, MOPAC is wholly licensed under LGPL, and I can add a note to the main README to that effect. According to the [instructions](https://www.gnu.org/licenses/gpl-howto.html) on the GNU website, both the `COPYING` (GPL) and `COPYING.lesser` (LGPL) files should be included in LGPL-licensed software because the LGPL license is an addendum to the GPL license rather than a self-contained legal document.

Thanks for catching the missing header, I'll fix that too.

**Comment by godotalgorithm** [comment]
Updates to the main `README` file should now resolve any license ambiguity.
