### ISSUE TITLE
Licence/Copyright issues

### ISSUE THREAD

**Issue by mbanck** [openmopac/mopac#144]
The Debian Linux distribution did a copyright/license audit before adding mopac to its package repository, and two issues came up:

1. `src/deprecated/Password.F90` has pretty obviously a lot of EULA/proprietary parts in it. As the directory names says, it is deprecated, could it be removed from the codebase? Unfortunately, Linux distributions need to care about source code being distributable under an open source license as well, not just the binaries, so the fact that this file is not compiled by default does not help much.
2. `src/makpol/standard.F90` has a weird `! 'All Rights Reserved, Copyright (C) Fujitsu Limited 1993.'` at the top of the `bangle` subroutine that is not (to my knowledge) in the original MOPAC7 source code, see e.g. https://github.com/lamoureux-lab/MOPAC/blob/master/xyzint.f#L341 Do you have an explanation for that? Can it be removed? I guess that subroutine is needed for at least `mopac-makpol`? "All Rights Reserved" implies this is proprietary code and would also make the codebase not distributable for us.

**Comment by godotalgorithm** [comment]
Thank you for bringing up these issues. I understand the importance of removing conflicting licensing statements to avoid confusion, even when they are practically irrelevant.

1. I can remove the old password system completely. I am overdue for cleaning out the deprecated directory, and there is no value in retaining that particular file any further.

2. The presence of that Fujitsu copyright statement is a relic from MOPAC's period of being commercially distributed by Fujitsu from approximately 1993-2001. Presumably there are versions of the entire MOPAC codebase from that period covered with such copyright statements. After leaving Fujitsu, the main developer of MOPAC, Jimmy Stewart, refactored the codebase, starting from the last open-source version in 1993, to produce his own commercial version of MOPAC that he distributed until recently donating it to this open-source project. The presence of that copyright statement almost certainly results from a lapse in code hygiene during that refactoring process. The original `makpol` program predates Fujitsu's acquisition of the codebase. The statement should not be there, it does not represent an intentional copyright notice for this version of MOPAC, and it can be safely removed.

I will promptly fix this in the main branch, and the changes will be reflected in MOPAC's next release.

**Comment by mbanck** [comment]
Many thanks for the prompt response!

In the meantime, I have uploded mopac to Debian with those two files (and thus also the makpol binary) removed, and it was accepted in the archive: https://tracker.debian.org/pkg/mopac I'll reinstate makpol when then next version is released without the two files.
