### ISSUE TITLE
Missing INDO CISD Output Block (as in MOPAC2016) in the new MOPAC v22.0.6

### ISSUE THREAD

**Issue by QuChem** [openmopac/mopac#149]
**Describe the bug**
Running ([one of the tests](https://github.com/openmopac/mopac/blob/main/tests/co_cisd.mop)) using MOPAC v22.0.6 will generate an output ([co_cisd.txt](https://github.com/openmopac/mopac/files/11407378/co_cisd.txt)) that is different from the existing ([output file](https://github.com/openmopac/mopac/blob/main/tests/co_cisd.out)) generated by MOPAC2016 (Version 20.173L) in a way that is lacking important information pertinent to INDO CISD energy values etc.

**To Reproduce**
Run the [test input file](https://github.com/openmopac/mopac/blob/main/tests/co_cisd.mop) with the two aforementioned versions of MOPAC.

**Expected behavior**
Lack of INDO CISD block of results in the output file generated by MOPAC v22.0.6

**Operating system**
macOS Ventura 13.3.1 (a) (22E772610a)

**Additional context**
N/A

**Comment by godotalgorithm** [comment]
This is one of several INDO tests that appears to have been orphaned - it is in the test directory, but I forgot to add it to the list of tests in the CMake script back when the INDO tests were first donated. There are logic barriers that suppress the standard MOPAC output block for INDO calculations, and they may have been added after the old test reference data was generated. I will activate these tests and make some decisions about these barriers. INDO is a spectroscopy model, so many of the standard outputs like heat of formation don't really mean anything and can give erratic and unphysical values. Some of the other observables might make more sense, but they still might not be intentional model outputs.
