### ISSUE TITLE
Systems consisting of a single metal ion don't output dielectric energy when EPS is used

### ISSUE THREAD

**Issue by aizvorski** [openmopac/mopac#235]
**Describe the bug**

Some systems consisting of a single metal ion only don't output dielectric energy in the results of the caluclation when the implicit solvent is enabled with the EPS keyword.  Aside from that the calculation runs and doesn't produce errors. Tested with K+, Na+, Mg++ Ca++.

Systems consisting of a halogen ion seem to behave normally.

**To Reproduce**

Input:
```
PM6-D3H4X XYZ 1SCF EPS=78.5 CHARGE=1


K 0.0 1 0.0 1 0.0 1
```

Output in .arc file:
```
           Empirical Formula: K  =     1 atoms

 PM6-D3H4X XYZ 1SCF EPS=78.5 CHARGE=1

     1SCF WAS SPECIFIED, SO BFGS WAS NOT USED                 
     SCF FIELD WAS ACHIEVED                                   

          HEAT OF FORMATION       =        109.07563 KCAL/MOL =     456.37245 KJ/MOL
          DIPOLE                  =          2.57000 DEBYE   POINT GROUP:  R3  
          NO. OF FILLED LEVELS    =          0
          CHARGE ON SYSTEM        =  *********
          IONIZATION POTENTIAL    =          0.000000 EV
          MOLECULAR WEIGHT        =         39.0983
          COSMO AREA              =        130.29 SQUARE ANGSTROMS
          COSMO VOLUME            =        139.85 CUBIC ANGSTROMS
```

"DIELECTRIC ENERGY" would normally be printed right after "HEAT OF FORMATION" but here it is missing.

"CHARGE ON SYSTEM" is also weird in the output, printed as *********  despite the CHARGE keyword being given, and the system having only one atom, which should make the charge assignment completely unambiguous.  

**Expected behavior**

As an example, using a chloride ion works normally:
Input:
```
PM6-D3H4X XYZ 1SCF EPS=78.4  CHARGE=-1


Cl 0.0 1 0.0 1 0.0 1
```

Output:
```
          HEAT OF FORMATION       =       -140.54239 KCAL/MOL =    -588.02938 KJ/MOL
          DIELECTRIC ENERGY       =         -3.48250 EV
          DIPOLE                  =          0.00000 DEBYE   POINT GROUP:  R3  
          NO. OF FILLED LEVELS    =          4
          CHARGE ON SYSTEM        =         -1
          IONIZATION POTENTIAL    =         10.832597 EV
          HOMO LUMO ENERGIES (EV) =        -10.833101.032
          MOLECULAR WEIGHT        =         35.4530
          COSMO AREA              =         52.81 SQUARE ANGSTROMS
          COSMO VOLUME            =         36.09 CUBIC ANGSTROMS
```

**Operating system**

OS is Ubuntu 22.04 LTS
MOPAC version is MOPAC v23.0.2 Linux, installed from conda-forge

```
$ conda list | grep mopac
mopac                     23.0.2               hc15f34f_0    conda-forge
```

**Additional context**

If EPS is omitted in the input, there is no "CHARGE ON SYSTEM" line at all - that seems a bit strange too

If CHARGES is included in the input (to try to debug the weird charge output), MOPAC crashes

**Comment by godotalgorithm** [comment]
These problematic examples have no valence electrons in them, which makes them atypical. If you tested every feature of every electronic structure code with zero active electrons, then you'd probably get a fair number of crashes and bizarre behavior. The total charge output is not defined in this case, causing the strange output. The dielectric energy is not being printed because it is zero. Many quantities in MOPAC are not printed when they are zero because their zero/non-zero value are the only readily available logical test for whether those quantities were calculated at all. COSMO solvent does have logical flags, so it doesn't actually need to rely on zero values as logical barriers.

I can't fix the failure to print zero values in MOPAC in general, as that is a part of its core design that would require a large overhaul of its control flow for a relatively small benefit. I can fix these problems for your examples and other systems with zero valence electrons.

**Comment by aizvorski** [comment]
@godotalgorithm Thank you for the quick reply and patch!

I compiled and tested the latest version with the fix (f444159) on the potassium ion example, and it produces a zero dielectric energy:

```
          HEAT OF FORMATION       =        109.07563 KCAL/MOL =     456.37245 KJ/MOL
          DIELECTRIC ENERGY       =          0.00000 EV
          DIPOLE                  =          0.00000 DEBYE   POINT GROUP:  R3  
          NO. OF FILLED LEVELS    =          0
          CHARGE ON SYSTEM        =         +1
```

So the differences are that the charge seems fine, and the dielectric energy is now printed, but the dielectric energy is still wrong.

Just as an experiment, I added a neon atom 100A away from the potassium ion (far enough it should have a negligible effect, and being a noble gas should also contribute zero to the dielectric energy). This makes the dielectric energy around -215 kJ/mol, both before (in mopac 23.02) and after the fix (f444159)

Input:
```
PM6-D3H4X XYZ 1SCF EPS=78.5 CHARGE=1


K 0 1 0 1 0 1
Ne 100 1 0 1 0 1
```

Output:
```
          HEAT OF FORMATION       =         57.54658 KCAL/MOL =     240.77490 KJ/MOL
          DIELECTRIC ENERGY       =         -2.23451 EV
```

That's more in line with the expected value of a few hundred kJ/mol.

**Comment by godotalgorithm** [comment]
I was assuming that a dielectric energy of zero was correct for an ion with zero valence electrons and didn't investigate further, but that now appears to have been a misunderstanding about some of the details of the COSMO model.

MOPAC's control flow is not well tested for zero valence electrons, and some of its features probably don't work in this case. For COSMO solvent, the solvent corrections are only activated in a block of code that presently only runs if there are valence electrons. I can repair this, but I can only realistically fix problems with zero valence electrons on a feature-by-feature basis as they are identified by users.

**Comment by godotalgorithm** [comment]
Just to clarify, my main point of confusion regarding different dielectric energy behavior for ions with or without valence electrons is related to a common problem in implicit solvent models caused by electronic density "leaking out" beyond the solvent accessible surface. With no valence electrons, there would be no explicit electronic charge to leak out. However, from some of your examples (e.g. neon) and inspecting the source code more carefully, it is clear that MOPAC's COSMO implementation is treating electronic charges as point charges/dipoles/quadrupoles when considering the electrostatics of the solvent accessible surface. This contrasts with how electronic charge is implicitly treated in the quantum mechanical calculation - the electron-electron interaction has a "Klopman-Ohno" form that decays to a point-charge interaction rather slowly and effectively corresponds to a rather diffuse distribution of electronic charge. If COSMO was using an electronic charge distribution that was more fully consistent with the QM calculation, there would be a substantial electronic charge leakage problem. Because it is using point charges, there is strictly zero leakage of electronic charge, which wouldn't be the case in an ab-initio QM calculation.

**Comment by aizvorski** [comment]
@godotalgorithm Thak you again!  I tried the latest version 00700cee31ee7f73e89f39be49784c1aebf0e495 and it works - output for potassium ion (without neon):

```
          HEAT OF FORMATION       =         57.54659 KCAL/MOL =     240.77495 KJ/MOL
          DIELECTRIC ENERGY       =         -2.23451 EV
```

Great!

The explanation for what's going on under the hood makes sense.  I hadn't heard of Klopman-Ohno specifically but of course a cavity relatively close to the atoms would have some of the diffuse electron density leak to outside.  The CPCM model in Orca (which does use diffuse distribution of charge) gives -208 kJ/mol for potassium in water, so the COSMO method here is quite close to that.  On the other hand the experimental enthalpy of hydration of potassium is -380 kJ/mol or so (most of which would be dielectric polarization).  So both COSMO and CPCM greatly underestimate polarization energy, but that's not a COSMO problem per se.

**Comment by godotalgorithm** [comment]
If you want implicit solvent models to be a bit more accurate for a limit set of applications with a common solvent and similar solutes, consider fitting an application-specific correction term that is linearly proportional to the solvent accessible surface area, which is provide in MOPAC output. The leading-order corrections beyond electrostatics-only solvent models are generally believed to have that behavior, and that sort of correction is one of the many ingredients of more sophisticated implicit solvent models such as [COSMO-RS](https://en.wikipedia.org/wiki/COSMO-RS).
